### ISSUE TITLE
Crash in DXE5 on resize docked Refactoring dialog 

### ISSUE THREAD

**Issue by AnselmoMS** [RRUZ/Delphi-IDE-Colorizer#8] opened 2015-09-26 14:43 UTC
[5061BF82]{vcl190.bpl  } Vcl.DockTabSet.TTabDockPanel.WMNCPaint (Line 1363, "Vcl.DockTabSet.pas" + 1) + $0
[5046777A]{vcl190.bpl  } Vcl.Controls.TWinControl.DefaultHandler (Line 10080, "Vcl.Controls.pas" + 30) + $19
[5061BF82]{vcl190.bpl  } Vcl.DockTabSet.TTabDockPanel.WMNCPaint (Line 1363, "Vcl.DockTabSet.pas" + 1) + $0
[50059970]{rtl190.bpl  } System.@FreeMem (Line 4364, "System.pas" + 20) + $0
[50060E05]{rtl190.bpl  } System.@UStrArrayClr (Line 23997, "System.pas" + 16) + $0
[1115661F]{DelphiIDEColorizer_XE5.dll} Colorizer.Hooks.Hooks.Detour_TWinControl_DefaultHandler$qqrp24Vcl.Controls.TWinControlpv (Line 598, "Colorizer.Hooks.pas" + 86) + $15
[50059970]{rtl190.bpl  } System.@FreeMem (Line 4364, "System.pas" + 20) + $0
[50060DA0]{rtl190.bpl  } System.@UStrClr (Line 23846, "System.pas" + 14) + $0
[111590E2]{DelphiIDEColorizer_XE5.dll} Colorizer.Hooks.Hooks.Detour_TWinControl_WMNCPaint$qqrp32Colorizer.Hooks.TWinControlClassr26Winapi.Messages.TWMNCPaint (Line 1713, "Colorizer.Hooks.pas" + 107) + $10
[5061BF82]{vcl190.bpl  } Vcl.DockTabSet.TTabDockPanel.WMNCPaint (Line 1363, "Vcl.DockTabSet.pas" + 1) + $0
[2185460B]{vclactnband190.bpl} Vcl.ActnMenus.CallWindowHook (Line 748, "Vcl.ActnMenus.pas" + 20) + $F
[50066917]{rtl190.bpl  } System.UnicodeFromLocaleChars (Line 37611, "System.pas" + 1) + $F
[5009413B]{rtl190.bpl  } System.SysUtils.AnsiCompareText (Line 6643, "System.SysUtils.pas" + 1) + $27
[1115F84F]{DelphiIDEColorizer_XE5.dll} Colorizer.Hook.Forms.Generics.Collections.%TDictionary__2$p24Vcl.Controls.TWinControlp40Colorizer.Vcl.Styles.TColorizerStyleHook%.GetBucketIndex$qqrxp24Vcl.Controls.TWinControli (Line 1641, "System.Generics.Collections.pas" + 19) + $6
[50467669]{vcl190.bpl  } Vcl.Controls.TWinControl.WndProc (Line 10039, "Vcl.Controls.pas" + 153) + $6
[111602CB]{DelphiIDEColorizer_XE5.dll} Colorizer.Hook.Forms.Generics.Collections.%TDictionary__2$p24Vcl.Controls.TWinControlp40Colorizer.Vcl.Styles.TColorizerStyleHook%.ContainsKey$qqrxp24Vcl.Controls.TWinControl (Line 1938, "System.Generics.Collections.pas" + 1) + $13
[5005EE66]{rtl190.bpl  } System.@IsClass (Line 15937, "System.pas" + 1) + $8
[1115ECA0]{DelphiIDEColorizer_XE5.dll} Colorizer.Hook.Forms.Hook.Forms.HandleColorizerStyleMessage$qqrp24Vcl.Controls.TWinControlr24Winapi.Messages.TMessageynpqqrr24Winapi.Messages.TMessage$v (Line 188, "Colorizer.Hook.Forms.pas" + 50) + $9
[1115EDDB]{DelphiIDEColorizer_XE5.dll} Colorizer.Hook.Forms.Hook.Forms.Detour_TWinControl_WndProc$qqrp37Colorizer.Hook.Forms.TWinControlClassr24Winapi.Messages.TMessage (Line 264, "Colorizer.Hook.Forms.pas" + 22) + $6
[50466CAC]{vcl190.bpl  } Vcl.Controls.TWinControl.MainWndProc (Line 9751, "Vcl.Controls.pas" + 3) + $6
[501749C4]{rtl190.bpl  } System.Classes.StdWndProc (Line 17010, "System.Classes.pas" + 5) + $0
[12A358D9]{cxLibraryRS19.bpl} Dxhooks. + $0
[50469DE1]{vcl190.bpl  } Vcl.Controls.TWinControl.SetBounds (Line 11779, "Vcl.Controls.pas" + 5) + $15
[5046A6FC]{vcl190.bpl  } Vcl.Controls.TWinControl.GetClientOrigin (Line 12136, "Vcl.Controls.pas" + 3) + $9
[50460AD3]{vcl190.bpl  } Vcl.Controls.TControl.SetBoundsRect (Line 5794, "Vcl.Controls.pas" + 1) + $19
[5061BECA]{vcl190.bpl  } Vcl.DockTabSet.TTabDockPanel.SplitterMouseMove (Line 1329, "Vcl.DockTabSet.pas" + 47) + $5
[504633D2]{vcl190.bpl  } Vcl.Controls.TControl.MouseMove (Line 7444, "Vcl.Controls.pas" + 1) + $1D
[5046345E]{vcl190.bpl  } Vcl.Controls.TControl.WMMouseMove (Line 7456, "Vcl.Controls.pas" + 8) + $22
[5005F063]{rtl190.bpl  } System.TObject.Dispatch (Line 16317, "System.pas" + 11) + $0
[50462B49]{vcl190.bpl  } Vcl.Controls.TControl.WndProc (Line 7224, "Vcl.Controls.pas" + 91) + $6
[50466E9F]{vcl190.bpl  } Vcl.Controls.TWinControl.IsControlMouseMsg (Line 9807, "Vcl.Controls.pas" + 1) + $9
[5045D8FA]{vcl190.bpl  } Vcl.Controls.FindControl (Line 3559, "Vcl.Controls.pas" + 6) + $9
[50467669]{vcl190.bpl  } Vcl.Controls.TWinControl.WndProc (Line 10039, "Vcl.Controls.pas" + 153) + $6
[111602CB]{DelphiIDEColorizer_XE5.dll} Colorizer.Hook.Forms.Generics.Collections.%TDictionary__2$p24Vcl.Controls.TWinControlp40Colorizer.Vcl.Styles.TColorizerStyleHook%.ContainsKey$qqrxp24Vcl.Controls.TWinControl (Line 1938, "System.Generics.Collections.pas" + 1) + $13
[5005EE66]{rtl190.bpl  } System.@IsClass (Line 15937, "System.pas" + 1) + $8
[1115ECA0]{DelphiIDEColorizer_XE5.dll} Colorizer.Hook.Forms.Hook.Forms.HandleColorizerStyleMessage$qqrp24Vcl.Controls.TWinControlr24Winapi.Messages.TMessageynpqqrr24Winapi.Messages.TMessage$v (Line 188, "Colorizer.Hook.Forms.pas" + 50) + $9
[1115EDDB]{DelphiIDEColorizer_XE5.dll} Colorizer.Hook.Forms.Hook.Forms.Detour_TWinControl_WndProc$qqrp37Colorizer.Hook.Forms.TWinControlClassr24Winapi.Messages.TMessage (Line 264, "Colorizer.Hook.Forms.pas" + 22) + $6
[50466CAC]{vcl190.bpl  } Vcl.Controls.TWinControl.MainWndProc (Line 9751, "Vcl.Controls.pas" + 3) + $6
[501749C4]{rtl190.bpl  } System.Classes.StdWndProc (Line 17010, "System.Classes.pas" + 5) + $0
[50590DC3]{vcl190.bpl  } Vcl.Forms.TApplication.ProcessMessage (Line 10288, "Vcl.Forms.pas" + 23) + $1
[50590E06]{vcl190.bpl  } Vcl.Forms.TApplication.HandleMessage (Line 10318, "Vcl.Forms.pas" + 1) + $4
[50591141]{vcl190.bpl  } Vcl.Forms.TApplication.Run (Line 10456, "Vcl.Forms.pas" + 26) + $3

**Comment by RRUZ** [comment] 2015-09-26 16:07
Can you please include the steps to reproduce the issue, and also the version of the plugin which you are using.

**Comment by RRUZ** [comment] 2017-09-17 16:48
Closing this because not additional feedback was received.

**Closed by RRUZ** 2017-09-17 16:48 UTC
